# Scaffolding generated by Casein v.3.1.11

module Casein
  class CanBoTrinhDosController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = Param.get_param_value("can_bo_trinh_do_index_page_title")
  		@can_bo_trinh_dos = CanBoTrinhDo.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = Param.get_param_value("can_bo_trinh_do_show_page_title")
      @can_bo_trinh_do = CanBoTrinhDo.find params[:id]
    end
 
    def new
      @casein_page_title = Param.get_param_value("can_bo_trinh_do_new_page_title")
    	@can_bo_trinh_do = CanBoTrinhDo.new
    end

    def create
      @can_bo_trinh_do = CanBoTrinhDo.new params[:can_bo_trinh_do]
    
      if @can_bo_trinh_do.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_can_bo_trinh_dos_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = Param.get_param_value("can_bo_trinh_do_update_page_title")
      
      @can_bo_trinh_do = CanBoTrinhDo.find params[:id]
    
      if @can_bo_trinh_do.update_attributes params[:can_bo_trinh_do]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_can_bo_trinh_dos_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @can_bo_trinh_do = CanBoTrinhDo.find params[:id]

      @can_bo_trinh_do.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_can_bo_trinh_dos_path
    end
  
  end
end