# Scaffolding generated by Casein v.3.1.11

module Casein
  class CapBacQuanDoisController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Cap bac quan dois'
  		@cap_bac_quan_dois = CapBacQuanDoi.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View cap bac quan doi'
      @cap_bac_quan_doi = CapBacQuanDoi.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new cap bac quan doi'
    	@cap_bac_quan_doi = CapBacQuanDoi.new
    end

    def create
      @cap_bac_quan_doi = CapBacQuanDoi.new params[:cap_bac_quan_doi]
    
      if @cap_bac_quan_doi.save
        flash[:notice] = 'Cap bac quan doi created'
        redirect_to casein_cap_bac_quan_dois_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new cap bac quan doi'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update cap bac quan doi'
      
      @cap_bac_quan_doi = CapBacQuanDoi.find params[:id]
    
      if @cap_bac_quan_doi.update_attributes params[:cap_bac_quan_doi]
        flash[:notice] = 'Cap bac quan doi has been updated'
        redirect_to casein_cap_bac_quan_dois_path
      else
        flash.now[:warning] = 'There were problems when trying to update this cap bac quan doi'
        render :action => :show
      end
    end
 
    def destroy
      @cap_bac_quan_doi = CapBacQuanDoi.find params[:id]

      @cap_bac_quan_doi.destroy
      flash[:notice] = 'Cap bac quan doi has been deleted'
      redirect_to casein_cap_bac_quan_dois_path
    end
  
  end
end