# Scaffolding generated by Casein v.3.1.11

module Casein
  class ChucVusController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Chuc vus'
  		@chuc_vus = ChucVu.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View chuc vu'
      @chuc_vu = ChucVu.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new chuc vu'
    	@chuc_vu = ChucVu.new
    end

    def create
      @chuc_vu = ChucVu.new params[:chuc_vu]
    
      if @chuc_vu.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_chuc_vus_path
      else
        flash.now[:warning] = Param.get_param_value("deleting_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update chuc vu'
      
      @chuc_vu = ChucVu.find params[:id]
    
      if @chuc_vu.update_attributes params[:chuc_vu]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_chuc_vus_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @chuc_vu = ChucVu.find params[:id]

      @chuc_vu.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_chuc_vus_path
    end
  
  end
end