# Scaffolding generated by Casein v.3.1.11

module Casein
  class DonVisController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Don vis'
  		@don_vis = DonVi.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View don vi'
      @don_vi = DonVi.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new don vi'
    	@don_vi = DonVi.new
    end

    def create
      @don_vi = DonVi.new params[:don_vi]
    
      if @don_vi.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_don_vis_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update don vi'
      
      @don_vi = DonVi.find params[:id]
    
      if @don_vi.update_attributes params[:don_vi]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_don_vis_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @don_vi = DonVi.find params[:id]

      @don_vi.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_don_vis_path
    end
  
  end
end