# Scaffolding generated by Casein v.3.1.11

module Casein
  class HocHamsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = Param.get_param_value("hoc_ham_index_page_title")
  		@hoc_hams = HocHam.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = Param.get_param_value("hoc_ham_show_page_title")
      @hoc_ham = HocHam.find params[:id]
    end
 
    def new
      @casein_page_title = Param.get_param_value("hoc_ham_new_page_title")
    	@hoc_ham = HocHam.new
    end

    def create
      @hoc_ham = HocHam.new params[:hoc_ham]
    
      if @hoc_ham.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_hoc_hams_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = Param.get_param_value("hoc_ham_update_page_title")
      
      @hoc_ham = HocHam.find params[:id]
    
      if @hoc_ham.update_attributes params[:hoc_ham]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_hoc_hams_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @hoc_ham = HocHam.find params[:id]

      @hoc_ham.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_hoc_hams_path
    end
  
  end
end