# Scaffolding generated by Casein v.3.1.11

module Casein
  class LoaiLaoDongsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Loai lao dongs'
  		@loai_lao_dongs = LoaiLaoDong.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View loai lao dong'
      @loai_lao_dong = LoaiLaoDong.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new loai lao dong'
    	@loai_lao_dong = LoaiLaoDong.new
    end

    def create
      @loai_lao_dong = LoaiLaoDong.new params[:loai_lao_dong]
    
      if @loai_lao_dong.save
        flash[:notice] = 'Loai lao dong created'
        redirect_to casein_loai_lao_dongs_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new loai lao dong'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update loai lao dong'
      
      @loai_lao_dong = LoaiLaoDong.find params[:id]
    
      if @loai_lao_dong.update_attributes params[:loai_lao_dong]
        flash[:notice] = 'Loai lao dong has been updated'
        redirect_to casein_loai_lao_dongs_path
      else
        flash.now[:warning] = 'There were problems when trying to update this loai lao dong'
        render :action => :show
      end
    end
 
    def destroy
      @loai_lao_dong = LoaiLaoDong.find params[:id]

      @loai_lao_dong.destroy
      flash[:notice] = 'Loai lao dong has been deleted'
      redirect_to casein_loai_lao_dongs_path
    end
  
  end
end