# Scaffolding generated by Casein v.3.1.11

module Casein
  class LoaiQuyetDinhsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = Param.get_param_value("loai_quyet_dinh_index_page_title")
  		@loai_quyet_dinhs = LoaiQuyetDinh.paginate :page => params[:page], :per_page => 10
    end
  
    def show
      @casein_page_title = Param.get_param_value("loai_quyet_dinh_show_page_title")
      @loai_quyet_dinh = LoaiQuyetDinh.find params[:id]
    end
 
    def new
      @casein_page_title = Param.get_param_value("loai_quyet_dinh_new_page_title")
    	@loai_quyet_dinh = LoaiQuyetDinh.new
    end

    def create
      @loai_quyet_dinh = LoaiQuyetDinh.new params[:loai_quyet_dinh]
    
      if @loai_quyet_dinh.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_loai_quyet_dinhs_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = Param.get_param_value("loai_quyet_dinh_update_page_title")
      
      @loai_quyet_dinh = LoaiQuyetDinh.find params[:id]
    
      if @loai_quyet_dinh.update_attributes params[:loai_quyet_dinh]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_loai_quyet_dinhs_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @loai_quyet_dinh = LoaiQuyetDinh.find params[:id]

      @loai_quyet_dinh.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_loai_quyet_dinhs_path
    end
  
  end
end