# Scaffolding generated by Casein v.3.1.11

module Casein
  class NgachesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Ngaches'
  		@ngaches = Ngach.paginate :page => params[:page]
      @ngaches_xls = Ngach.all

      respond_to do |format|
        format.html
        format.xls{
          ngach = Spreadsheet::Workbook.new
          list = ngach.create_worksheet :name => 'Danh sach Ngach'
          list.row(0).concat %w{Ma_ngach ten_ngach Nien_han ghi_chu}
          @ngaches_xls.each_with_index { |ct, i|
            list.row(i+1).push(ct.ma_ngach, ct.ten_ngach,ct.nien_han,ct.ghi_chu)
          }

          header_format = Spreadsheet::Format.new :color => :green, :weight => :bold
          list.row(0).default_format = header_format
          #output to blob object
          blob = StringIO.new("")
          ngach.write blob
          #respond with blob object as a file
          send_data blob.string, :type => :xls, :filename => "Danh_Sach_Ngach.xls"
        }
      end
    end
  
    def show
      @casein_page_title = 'View ngach'
      @ngach = Ngach.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new ngach'
    	@ngach = Ngach.new
    end

    def create
      @ngach = Ngach.new params[:ngach]
    
      if @ngach.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_ngaches_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update ngach'
      
      @ngach = Ngach.find params[:id]
    
      if @ngach.update_attributes params[:ngach]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_ngaches_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @ngach = Ngach.find params[:id]

      @ngach.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_ngaches_path
    end
    def import_from_excel
      @casein_page_title = Param.get_param_value("ngach_import_from_excel_page_title")
    end

    def parse_save_from_excel
      file_path = params[:excel_file]
      file = XlsUploader.new
      file.store!(file_path)

      book = Spreadsheet.open "public/#{file.store_path}"

      sheet = book.worksheet 0  # first sheet in the spreadsheet file will be used

      @errors = Hash.new
      @counter = 0
      @commit = 0
      @wrong = 0
      sheet.each 1 do |row|
        @counter += 1
        p = Ngach.new
        p.ma_ngach = row[0].to_s
        p.ten_ngach = row[1].to_s
        p.nien_han =  row[2].to_i
        p.ghi_chu = row[3].to_s
        if p.valid?
          @commit += 1
          p.save
        else
          @wrong += 1
          @errors["#{@counter + 1}"] = "CB.#{row[0].to_i.to_s} - #{row[1].to_s}"
        end
      end
      book.io.close
      if @wrong == 0
        flash[:notice] = "#{Param.get_param_value "import_success"} | #{Param.get_param_value "commit"}: #{@commit}/#{@counter} | #{Param.get_param_value "wrong"}: #{@wrong}"
        file.remove!
        redirect_to casein_ngaches_path
      else
        flash[:notice] = "#{Param.get_param_value "import_success"} | #{Param.get_param_value "commit"}: #{@commit}/#{@counter} | #{Param.get_param_value "wrong"}: #{@wrong}"
        file.remove!
        render :action => 'show_result', :errors => @errors
      end

    end

    def show_result
      @casein_page_title = Param.get_param_value("ngach_show_result_page_title")
      @errors = Hash.new
      @errors = params[:errors]
      respond_to do |format|
        format.html
        format.json {head :no_content}
      end
    end
  end
end