# Scaffolding generated by Casein v.3.1.11

module Casein
  class NgachesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Ngaches'
  		@ngaches = Ngach.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View ngach'
      @ngach = Ngach.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new ngach'
    	@ngach = Ngach.new
    end

    def create
      @ngach = Ngach.new params[:ngach]
    
      if @ngach.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_ngaches_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update ngach'
      
      @ngach = Ngach.find params[:id]
    
      if @ngach.update_attributes params[:ngach]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_ngaches_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @ngach = Ngach.find params[:id]

      @ngach.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_ngaches_path
    end
  
  end
end