# Scaffolding generated by Casein v.3.1.11

module Casein
  class CongViecsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Cong viecs'
  		@cong_viecs = CongViec.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View cong viec'
      @cong_viec = CongViec.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new cong viec'
    	@cong_viec = CongViec.new
    end

    def create
      @cong_viec = CongViec.new params[:cong_viec]
    
      if @cong_viec.save
        flash[:notice] = 'Cong viec created'
        redirect_to casein_cong_viecs_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new cong viec'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update cong viec'
      
      @cong_viec = CongViec.find params[:id]
    
      if @cong_viec.update_attributes params[:cong_viec]
        flash[:notice] = 'Cong viec has been updated'
        redirect_to casein_cong_viecs_path
      else
        flash.now[:warning] = 'There were problems when trying to update this cong viec'
        render :action => :show
      end
    end
 
    def destroy
      @cong_viec = CongViec.find params[:id]

      @cong_viec.destroy
      flash[:notice] = 'Cong viec has been deleted'
      redirect_to casein_cong_viecs_path
    end
  
  end
end