# Scaffolding generated by Casein v.3.1.11

module Casein
  class LichSuBacLuongsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
=begin  
    def index
      @casein_page_title = Param.get_param_value "lich_su_bac_luong_index_page_title"
      search_value = params["keyword"]
      if search_value != nil
        @lich_su_bac_luongs = LichSuBacLuong.search(search_value).paginate(:per_page => 10, :page => params[:page],:order=> :can_bo_thong_tin_id)
        @lich_su_bac_luongs_xls = LichSuBacLuong.search(search_value)
        if @lich_su_bac_luongs.count == 0
          flash.now[:warning] = Param.get_param_value("searching_has_no_result")
          @lich_su_bac_luongs = LichSuBacLuong.paginate :page => params[:page], :per_page => 10 ,:order=> :can_bo_thong_tin_id
          @lich_su_bac_luongs_xls = LichSuBacLuong.all
        else
          flash.now[:notice] = "#{Param.get_param_value("number_searching_result")} #{@lich_su_bac_luongs.count}"
        end
      else
        @lich_su_bac_luongs = LichSuBacLuong.paginate :page => params[:page], :per_page => 10 ,:order=> :can_bo_thong_tin_id
        @lich_su_bac_luongs_xls = LichSuBacLuong.all
      end

      respond_to do |format|
        format.html
        format.xls {
          can_bo = Spreadsheet::Workbook.new
          list = can_bo.create_worksheet :name => 'Lich Su Bac Luong'
          list.row(0).concat %w{Ma_can_bo Can_bo Ngach Bac_luong Ngay_thay_doi Ghi_chu}
          @lich_su_bac_luongs_xls.each_with_index { |lichsu, i|
            list.row(i+1).push lichsu.can_bo_thong_tin.ma_cb,lichsu.can_bo_thong_tin.ho_ten,lichsu.bac_luong.ngach.ten_ngach,lichsu.bac_luong.bac,lichsu.ngay_thay_doi_bac,lichsu.ghi_chu
          }
          header_format = Spreadsheet::Format.new :color => :green, :weight => :bold
          list.row(0).default_format = header_format
          #output to blob object
          blob = StringIO.new("")
          can_bo.write blob
          #respond with blob object as a file
          send_data blob.string, :type => :xls, :filename => "LichSuBacLuong.xls"
        }
      end

  		#@lich_su_bac_luongs = LichSuBacLuong.paginate :page => params[:page]
    end
=end

	def index
      search_value = params["keyword"]
      view = 10
      don_vi = 0
      page = params[:page] ||= 1

      if params["num_view"].to_s != ""
        #must be a number
        if params["num_view"].match(/^\d+$/)
          #must be greater than 0 
          if params["num_view"].to_i > 0
            #set view value for pagination
            view = params["num_view"].to_i
          end
        end
      end

      if params[:don_vi]
        don_vi = params[:don_vi].to_i if params[:don_vi].match(/^\d+$/)
      end

      order = ""
      if params["order_by"].to_s != ""
        order = params["order_by"]
        #ignore the invalid values for order queries
        if order.split(":").last != "desc" && order.split(":").count > 1
          order = ""
        else
          #convert to correct format
          #param values has been submited include colon symbol
          #e.g: order by query desc
          order = order.gsub(':', ' ')
        end
      end

      #set conditions for paginate to filter records, it's base on don_vi parameter
      paginate_conditions = ""
      paginate_conditions = ['don_vi_id = ?', don_vi] if don_vi != 0

      @can_bos = CanBoThongTin.select("id, ma_cb, ho_ten, ngay_sinh, don_vi_id, chuc_vu_id, loai_lao_dong_id").search(search_value, don_vi).paginate :page => page, :per_page => view, :conditions => paginate_conditions
    end
	
	 def details
      ma_cb = params[:ma_cb]
      can_bo_thong_tin = CanBoThongTin.find_by_ma_cb(ma_cb)
      if can_bo_thong_tin
        @can_bo_thong_tin = can_bo_thong_tin
        @lich_su_bac_luongs =  LichSuBacLuong.find_all_by_can_bo_thong_tin_id(can_bo_thong_tin.id)
      else
        render_404
      end
    end
	
    def show
      @casein_page_title = Param.get_param_value "lich_su_bac_luong_show_page_title"
      @lich_su_bac_luong = LichSuBacLuong.find params[:id]
      @lich_su_bac_luong.ngach_sl = @lich_su_bac_luong.bac_luong.ngach_id
      @lich_su_bac_luong.bac_sl = @lich_su_bac_luong.bac_luong.bac
    end

    def edit
      @casein_page_title = Param.get_param_value "lich_su_bac_luong_edit_page_title"
      @lich_su_bac_luong = LichSuBacLuong.find params[:id]
      @lich_su_bac_luong.ngach_sl = @lich_su_bac_luong.bac_luong.ngach_id
      @lich_su_bac_luong.bac_sl = @lich_su_bac_luong.bac_luong.bac
      @lich_su_bac_luong.so_quyet_dinh = @lich_su_bac_luong.quyet_dinh.so_qd
    end
 
    def new
      @casein_page_title = Param.get_param_value "lich_su_bac_luong_new_page_title"
  	  @lich_su_bac_luong = LichSuBacLuong.new
  	  if params[:ma_cb]
        cb = CanBoThongTin.find_by_ma_cb(params[:ma_cb])
        if cb
          @lich_su_bac_luong.can_bo_thong_tin_id = cb.id
          @is_edited = true
        end
      end
    end

    def create

      @lich_su_bac_luong = LichSuBacLuong.new params[:lich_su_bac_luong]
      bacluong_id = LichSuBacLuong.get_bl_id(@lich_su_bac_luong.ngach_sl, @lich_su_bac_luong.bac_sl)
      quyetdinh_id= QuyetDinh.find_by_so_qd(@lich_su_bac_luong.so_quyet_dinh)
      if bacluong_id
         @lich_su_bac_luong.bac_luong_id = bacluong_id
      end
      if @lich_su_bac_luong.valid? && quyetdinh_id
          @lich_su_bac_luong.quyet_dinh_id = quyetdinh_id.id
          if @lich_su_bac_luong.save
            bac_luong_id = @lich_su_bac_luong.bac_luong_id
            p = CanBoThongTin.find(@lich_su_bac_luong.can_bo_thong_tin_id)
            if p
              p.update_attribute(:bac_luong_id, bac_luong_id)
            end

            flash[:notice] = Param.get_param_value("adding_success")
            redirect_to casein_lich_su_bac_luongs_path
          else
            flash.now[:warning] = Param.get_param_value("adding_false")
            render :action => :new
          end
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = Param.get_param_value "lich_su_bac_luong_update_page_title"
      
      @lich_su_bac_luong = LichSuBacLuong.find params[:id]

      bacluong_id = LichSuBacLuong.get_bl_id(params[:lich_su_bac_luong][:ngach_sl],params[:lich_su_bac_luong][:bac_sl])

      if bacluong_id
        params[:lich_su_bac_luong][:bac_luong_id] = bacluong_id
      end


      if @lich_su_bac_luong.update_attributes params[:lich_su_bac_luong]
        quyetdinh = QuyetDinh.find_by_so_qd(params[:lich_su_bac_luong][:so_quyet_dinh])
        if quyetdinh 
          @lich_su_bac_luong.update_attribute(:quyet_dinh_id, quyetdinh.id)
        end

        lich_su_last = LichSuBacLuong.get_last(@lich_su_bac_luong.can_bo_thong_tin_id)
        if lich_su_last.id == @lich_su_bac_luong.id
          bac_luong_id = @lich_su_bac_luong.bac_luong_id
          p = nil
          p = CanBoThongTin.find(@lich_su_bac_luong.can_bo_thong_tin_id)
          if p != nil
            p.update_attribute(:bac_luong_id, bac_luong_id)
          end
        end
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_lich_su_bac_luongs_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @lich_su_bac_luong = LichSuBacLuong.find params[:id]

      @lich_su_bac_luong.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_lich_su_bac_luongs_path
    end
    def import_from_excel
      @casein_page_title = Param.get_param_value("lich_su_bac_luong_import_from_excel_page_title")
    end

    def parse_save_from_excel
      if params[:excel_file]
      file_path = params[:excel_file]
      file = XlsUploader.new
      file.store!(file_path)

      book = Spreadsheet.open "public/#{file.store_path}"

      sheet = book.worksheet 0  # first sheet in the spreadsheet file will be used

      @errors = Hash.new
      @counter = 0
      @commit = 0
      @wrong = 0
      sheet.each 1 do |row|
        @counter += 1
        p = LichSuBacLuong.new
        canbo = CanBoThongTin.find_by_ma_cb(row[0].to_i.to_s)
        if canbo
          p.can_bo_thong_tin_id = canbo.id
          p.ngay_thay_doi_bac = row[4].to_date
          p.ghi_chu = row[5].to_s

          ngach = Ngach.find_by_ten_ngach(row[2].to_s)
          if ngach
            bl = BacLuong.find(:first, :conditions =>['ngach_id = ? and bac = ?', ngach.id , row[3].to_i])
            if bl
                 p.bac_luong_id = bl.id
            else
              @wrong += 1
              @errors["#{@counter + 1}"] = "CB.#{row[0].to_i.to_s} - #{row[1].to_s}"
            end
          else
            @wrong += 1
            @errors["#{@counter + 1}"] = "CB.#{row[0].to_i.to_s} - #{row[1].to_s}"
          end

          if p.valid?
            @commit += 1
            p.save
          else
            @wrong += 1
            @errors["#{@counter + 1}"] = "CB.#{row[0].to_i.to_s} - #{row[1].to_s}"
          end
        else
          @wrong += 1
          @errors["#{@counter + 1}"] = "CB.#{row[0].to_i.to_s} - #{row[1].to_s}"
        end
      end
      book.io.close
      if @wrong == 0
        flash[:notice] = "#{Param.get_param_value "import_success"} | #{Param.get_param_value "commit"}: #{@commit}/#{@counter} | #{Param.get_param_value "wrong"}: #{@wrong}"
        file.remove!
        redirect_to casein_lich_su_bac_luongs_path
      else
        flash[:notice] = "#{Param.get_param_value "import_success"} | #{Param.get_param_value "commit"}: #{@commit}/#{@counter} | #{Param.get_param_value "wrong"}: #{@wrong}"
        file.remove!
        render :action => 'show_result', :errors => @errors
      end

      else #if :excel_file is null
        flash[:warning] = Param.get_param_value ("let_choose_file_now")
        redirect_to import_from_excel_casein_lich_su_bac_luongs_path
      end

    end

    def show_result
      @casein_page_title = Param.get_param_value("can_bo_li_lich_ct_show_result_page_title")
      @errors = Hash.new
      @errors = params[:errors]
      respond_to do |format|
        format.html
        format.json {head :no_content}
      end
    end
  end
end