# Scaffolding generated by Casein v.3.1.11

module Casein
  class LyLuanChinhTrisController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = Param.get_param_value("ly_luan_chinh_tri_index_page_title")
  		@ly_luan_chinh_tris = LyLuanChinhTri.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = Param.get_param_value("ly_luan_chinh_tri_show_page_title")
      @ly_luan_chinh_tri = LyLuanChinhTri.find params[:id]
    end
 
    def new
      @casein_page_title = Param.get_param_value("ly_luan_chinh_tri_new_page_title")
    	@ly_luan_chinh_tri = LyLuanChinhTri.new
    end

    def create
      @ly_luan_chinh_tri = LyLuanChinhTri.new params[:ly_luan_chinh_tri]
    
      if @ly_luan_chinh_tri.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_ly_luan_chinh_tris_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = Param.get_param_value("ly_luan_chinh_tri_update_page_title")
      
      @ly_luan_chinh_tri = LyLuanChinhTri.find params[:id]
    
      if @ly_luan_chinh_tri.update_attributes params[:ly_luan_chinh_tri]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_ly_luan_chinh_tris_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @ly_luan_chinh_tri = LyLuanChinhTri.find params[:id]

      @ly_luan_chinh_tri.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_ly_luan_chinh_tris_path
    end
  
  end
end