# Scaffolding generated by Casein v.3.1.11

module Casein
  class NgoaiNgusController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = Param.get_param_value("ngoai_ngu_index_page_title")
  		@ngoai_ngus = NgoaiNgu.paginate :page => params[:page], :per_page => 10
    end
  
    def show
      @casein_page_title = Param.get_param_value("ngoai_ngu_show_page_title")
      @ngoai_ngu = NgoaiNgu.find params[:id]
    end
 
    def new
      @casein_page_title = Param.get_param_value("ngoai_ngu_new_page_title")
    	@ngoai_ngu = NgoaiNgu.new
    end

    def create
      @ngoai_ngu = NgoaiNgu.new params[:ngoai_ngu]
    
      if @ngoai_ngu.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_ngoai_ngus_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = Param.get_param_value("ngoai_ngu_update_page_title")
      
      @ngoai_ngu = NgoaiNgu.find params[:id]
    
      if @ngoai_ngu.update_attributes params[:ngoai_ngu]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_ngoai_ngus_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @ngoai_ngu = NgoaiNgu.find params[:id]

      @ngoai_ngu.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_ngoai_ngus_path
    end
  
  end
end