# Scaffolding generated by Casein v.3.1.11

module Casein
  class QuanLyNhaNuocsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = Param.get_param_value("quan_ly_nha_nuoc_index_page_title")
  		@quan_ly_nha_nuocs = QuanLyNhaNuoc.paginate :page => params[:page], :per_page => 10
    end
  
    def show
      @casein_page_title = Param.get_param_value("quan_ly_nha_nuoc_show_page_title")
      @quan_ly_nha_nuoc = QuanLyNhaNuoc.find params[:id]
    end
 
    def new
      @casein_page_title = Param.get_param_value("quan_ly_nha_nuoc_new_page_title")
    	@quan_ly_nha_nuoc = QuanLyNhaNuoc.new
    end

    def create
      @quan_ly_nha_nuoc = QuanLyNhaNuoc.new params[:quan_ly_nha_nuoc]
    
      if @quan_ly_nha_nuoc.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_quan_ly_nha_nuocs_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = Param.get_param_value("quan_ly_nha_nuoc_update_page_title")
      
      @quan_ly_nha_nuoc = QuanLyNhaNuoc.find params[:id]
    
      if @quan_ly_nha_nuoc.update_attributes params[:quan_ly_nha_nuoc]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_quan_ly_nha_nuocs_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @quan_ly_nha_nuoc = QuanLyNhaNuoc.find params[:id]

      @quan_ly_nha_nuoc.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_quan_ly_nha_nuocs_path
    end
  
  end
end