# Scaffolding generated by Casein v.3.1.11

module Casein
  class QuyetDinhsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = Param.get_param_value("quyet_dinh_index_page_title")
      search_value = params["keyword"]
      if search_value != nil
        @quyet_dinhs = QuyetDinh.search(search_value).paginate(:per_page => 10, :page => params[:page])
        if @quyet_dinhs.count == 0
          flash.now[:warning] = Param.get_param_value("searching_has_no_result")
          @quyet_dinhs = QuyetDinh.paginate :page => params[:page], :per_page => 10
        else
          flash.now[:notice] = "#{Param.get_param_value("number_searching_result")} #{@quyet_dinhs.count}"
        end
      else
        @quyet_dinhs = QuyetDinh.paginate :page => params[:page], :per_page => 10
      end
    end
  
    def show
      @casein_page_title = Param.get_param_value("quyet_dinh_show_page_title")
      @quyet_dinh = QuyetDinh.find params[:id]
    end
 
    def new
      @casein_page_title = Param.get_param_value("quyet_dinh_new_page_title")
    	@quyet_dinh = QuyetDinh.new
    end

    def create
      @quyet_dinh = QuyetDinh.new params[:quyet_dinh]
    
      if @quyet_dinh.save
        flash[:notice] = Param.get_param_value("adding_success")
        redirect_to casein_quyet_dinhs_path
      else
        flash.now[:warning] = Param.get_param_value("adding_false")
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = Param.get_param_value("quyet_dinh_update_page_title")
      
      @quyet_dinh = QuyetDinh.find params[:id]
    
      if @quyet_dinh.update_attributes params[:quyet_dinh]
        flash[:notice] = Param.get_param_value("updating_success")
        redirect_to casein_quyet_dinhs_path
      else
        flash.now[:warning] = Param.get_param_value("updating_false")
        render :action => :show
      end
    end
 
    def destroy
      @quyet_dinh = QuyetDinh.find params[:id]

      @quyet_dinh.destroy
      flash[:notice] = Param.get_param_value("deleting_success")
      redirect_to casein_quyet_dinhs_path
    end
  
  end
end