# Scaffolding generated by Casein v.3.1.11

module Casein
  class ThanNhansController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]


    def index
      @casein_page_title = 'Than nhans'
  		@than_nhans = ThanNhan.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View than nhan'
      @than_nhan = ThanNhan.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new than nhan'
    	@than_nhan = ThanNhan.new
    end

    def create
      @than_nhan = ThanNhan.new params[:than_nhan]
    
      if @than_nhan.save
        flash[:notice] = 'Than nhan created'
        redirect_to casein_than_nhans_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new than nhan'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update than nhan'
      
      @than_nhan = ThanNhan.find params[:id]
    
      if @than_nhan.update_attributes params[:than_nhan]
        flash[:notice] = 'Than nhan has been updated'
        redirect_to casein_than_nhans_path
      else
        flash.now[:warning] = 'There were problems when trying to update this than nhan'
        render :action => :show
      end
    end
 
    def destroy
      @than_nhan = ThanNhan.find params[:id]

      @than_nhan.destroy
      flash[:notice] = 'Than nhan has been deleted'
      redirect_to casein_than_nhans_path
    end
  
  end
end